### ISSUE TITLE
Stop printing to line n. 150.

### ISSUE THREAD

**Issue by HalfSkin** [mochizukikotaro/print-code#1]
Hi,
why in my pc the plugin stop printing (html code) to line n. 150? 
Atom version is 1.15.0 ia32

Thx,
HS.

**Comment by mochizukikotaro** [comment]
@HalfSkin 

I am so sorry for the late reply....

I released version 0.6.1 to fix this issue.

But,  there may still be another bug.  So I will try fix https://github.com/mochizukikotaro/print-code/issues/3
